CI: run cabal update before cabal build
... to hopefully fix CI.

The latest version of cabal returns this without the update first:

Run cabal build
  cabal build
  shell: /usr/bin/bash -e {0}
Error: [Cabal-7160]
The package list for 'hackage.haskell.org' does not exist. Run 'cabal update' to download it.